stages:
  - test
  - release

variables:
  XDG_CACHE_HOME: : "${CI_PROJECT_DIR}/.cache"

.venv:
  before_script:
    - pip install poetry
    - poetry config settings.virtualenvs.in-project true
    - poetry install -vv
  cache:
    - key:
      prefix: "cache"
      paths:
        - .cache

    - key:
        prefix: "venv"
        files:
          - poetry.lock
          - pyproject.toml
      paths:
        - .venv


test:
  extends:
    - .venv
  stage: test
  image: ${IMAGE}
  script:
    - poetry run pytest -x tests/
  parallel:
    matrix:
      - IMAGE: python:3.8
      - IMAGE: python:3.10
      - IMAGE: python:3.11
