stages:
  - test
  - release

variables:
  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/.cache"

.venv:
  before_script:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install -vv
  cache:
    - key: cache
      paths:
        - .cache

    - key:
        prefix: venv
        files:
          - poetry.lock
          - pyproject.toml
      paths:
        - .venv

test:
  extends:
    - .venv
  stage: test
  image: ${IMAGE}
  script:
    - poetry run pytest -x tests/
  parallel:
    matrix:
      - IMAGE: python:3.8
      - IMAGE: python:3.10
      - IMAGE: python:3.11

release:
  extends:
    - .venv
  stage: release
  image: python:3.11
  only:
    - tags
  script:
    - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry publish -r gitlab